"""MITRE ATT&CK dataset loader, validator, and coverage computation.

The repo ships a trimmed JSON matrix (``app/rules/data/mitre_enterprise.json``)
generated by ``scripts/fetch_mitre_matrix.py``. It lists every top-level
Enterprise technique bucketed under each of the 14 canonical tactics
(ATT&CK v12+ order, ATT&CK v18.1 by default). Sub-techniques are NOT listed
in the matrix — they are accepted by the validator via prefix resolution
(e.g. ``T1059.001`` is allowed iff ``T1059`` exists).

Three public entry points:

* :func:`load_matrix` — cached loader. Returns the parsed dataset or
  ``None`` when the file is missing/unparseable (callers should treat that
  as a 503 condition).
* :func:`validate_mitre` — pure validator used by the rule create/update
  path. Returns ``(ok, message)`` so callers can decide HTTP status code.
* :func:`compute_full_coverage` — Detection Coverage dashboard payload:
  joins rule YAMLs against the dataset, overlays alert activity from the
  JSONL alert log, and returns the full Navigator-style matrix (covered
  cells + gaps).

The legacy :func:`compute_coverage` is preserved unchanged for the
existing ``/rules/mitre-coverage`` endpoint.
"""
from __future__ import annotations

import json
import logging
import re
from functools import lru_cache
from pathlib import Path
from typing import Iterable, Optional

import yaml

log = logging.getLogger(__name__)

# Canonical ATT&CK Enterprise tactic ORDER (ATT&CK v12+). Reused by both the
# matrix loader and the rule validator. Tactics in the dataset that aren't
# in this list are skipped with a warning log — keeps the validator strict
# (rule YAMLs can ONLY reference these) while still surviving dataset drift.
_TACTICS = [
    "Reconnaissance", "Resource Development", "Initial Access", "Execution",
    "Persistence", "Privilege Escalation", "Defense Evasion", "Credential Access",
    "Discovery", "Lateral Movement", "Collection", "Command and Control",
    "Exfiltration", "Impact",
]
_TACTIC_SET = set(_TACTICS)

# Top-level technique regex; sub-technique regex allows an optional .NNN suffix.
_TECH_RE = re.compile(r"^T\d{4}$")
_SUBTECH_RE = re.compile(r"^T\d{4}\.\d{3}$")
_TECH_OR_SUBTECH_RE = re.compile(r"^T\d{4}(\.\d{3})?$")

# Repo-bundled matrix path (relative to this file). Override via
# ``TINYSIEM_MITRE_MATRIX_PATH`` if you ship a custom matrix.
_REPO_MATRIX_PATH = Path(__file__).parent / "data" / "mitre_enterprise.json"


# ── Dataset loader ──────────────────────────────────────────────────────────


@lru_cache(maxsize=1)
def load_matrix(path: Optional[str] = None) -> Optional[dict]:
    """Load and cache the MITRE matrix JSON.

    Returns ``None`` if the file is missing or unparseable (and clears the
    cache so a later call can retry once the file is in place). Callers
    MUST handle ``None`` — typically as a 503 with a clear message.
    """
    resolved = _resolve_matrix_path(path)
    if resolved is None or not resolved.exists():
        log.warning("MITRE matrix file not found (looked at %s)", resolved)
        load_matrix.cache_clear()
        return None
    try:
        with resolved.open() as fh:
            data = json.load(fh)
    except (OSError, json.JSONDecodeError) as exc:
        log.warning("MITRE matrix at %s is unparseable: %s", resolved, exc)
        load_matrix.cache_clear()
        return None
    if not isinstance(data, dict) or "tactics" not in data:
        log.warning("MITRE matrix at %s has unexpected shape", resolved)
        return None
    return data


def _resolve_matrix_path(path: Optional[str]) -> Optional[Path]:
    """Honor an explicit override (settings), otherwise fall back to the
    repo-bundled file. Empty string == use the default.
    """
    from app.config import settings

    raw = (path if path is not None else settings.tinysiem_mitre_matrix_path) or ""
    if raw.strip():
        return Path(raw).expanduser()
    return _REPO_MATRIX_PATH


def matrix_path() -> Optional[Path]:
    """Return the matrix path the loader will try, or ``None`` if unset."""
    return _resolve_matrix_path(None)


def reset_matrix_cache() -> None:
    """Clear the LRU cache. Intended for tests."""
    load_matrix.cache_clear()


# ── Validator ──────────────────────────────────────────────────────────────


def validate_mitre(tactic: Optional[str], technique: Optional[str]) -> tuple[bool, str]:
    """Validate a (tactic, technique) pair against the bundled matrix.

    Rules (per the Detection Coverage spec):

    1. If both are ``None``/empty → rule is unmapped but ALLOWED.
    2. Exactly one of the two present → reject (must come as a pair).
    3. tactic must be in ``_TACTICS`` (case-sensitive exact).
    4. technique must match ``^T\\d{4}(\\.\\d{3})?$`` (sub-techniques allowed).
    5. The technique must appear in the dataset; the declared tactic must be
       one of its tactics. Sub-technique ``.NNN`` is resolved against its
       PREFIX technique's tactic list (e.g. ``T1059.001`` → tactics of ``T1059``).
    """
    if not tactic and not technique:
        return True, ""
    if bool(tactic) != bool(technique):
        return False, "mitre_tactic and mitre_technique must be specified together (both or neither)"
    if tactic not in _TACTIC_SET:
        return False, f"mitre_tactic {tactic!r} is not a valid ATT&CK Enterprise tactic"
    if not _TECH_OR_SUBTECH_RE.match(technique or ""):
        return False, f"mitre_technique {technique!r} must match pattern T0000 or T0000.000"

    matrix = load_matrix()
    if matrix is None:
        # Without a dataset we can only do the cheap structural checks above.
        # Reject with a clear message so users know to refresh the matrix.
        return False, "MITRE matrix dataset unavailable — run scripts/fetch_mitre_matrix.py"

    # Sub-technique: resolve against prefix technique's tactic list.
    base_id = technique.split(".", 1)[0] if "." in (technique or "") else technique

    # Build (id -> set(tactics)) once per call; matrix is small (≤207 ids).
    id_to_tactics: dict[str, set[str]] = {}
    for tac in matrix.get("tactics", []):
        tname = tac.get("tactic")
        for tech in tac.get("techniques", []):
            id_to_tactics.setdefault(tech["id"], set()).add(tname)

    if base_id not in id_to_tactics:
        return False, f"mitre_technique {technique!r} (base {base_id!r}) is not in the MITRE matrix dataset"
    valid_tactics = id_to_tactics[base_id]
    if tactic not in valid_tactics:
        return False, (
            f"technique {technique!r} belongs to tactics {sorted(valid_tactics)}, "
            f"not {tactic!r}"
        )
    return True, ""


# ── Legacy /rules/mitre-coverage entry point (unchanged) ───────────────────


def compute_coverage(rule_files: list[tuple[Path, bool]]) -> dict:
    """Aggregate built-in + custom rule MITRE tagging.

    Preserved verbatim for ``GET /rules/mitre-coverage`` — the new
    Detection Coverage endpoint is a separate module.
    """
    tactic_map: dict[str, dict[str, dict]] = {t: {} for t in _TACTICS}
    for path, _is_custom in rule_files:
        try:
            data = yaml.safe_load(path.read_text())
        except (yaml.YAMLError, OSError) as exc:
            log.warning("skipping unreadable rule file %s: %s", path, exc)
            continue
        if not isinstance(data, dict):
            continue
        tactic = data.get("mitre_tactic")
        technique = data.get("mitre_technique")
        if not tactic or not technique or tactic not in tactic_map:
            continue
        entry = tactic_map[tactic].setdefault(technique, {"count": 0, "rules": []})
        entry["count"] += 1
        entry["rules"].append(data.get("name", path.stem))
    return {
        "tactics": [
            {
                "tactic": t,
                "techniques": [
                    {"technique": tech, "count": v["count"], "rules": v["rules"]}
                    for tech, v in sorted(techniques.items())
                ],
            }
            for t, techniques in tactic_map.items()
        ]
    }


# ── Detection Coverage dashboard computation ───────────────────────────────


def compute_full_coverage(
    rule_files: Iterable[tuple[Path, bool]],
    alert_counts_by_technique: dict[str, int],
    alerts_unmapped: int,
) -> Optional[dict]:
    """Build the full Detection Coverage matrix payload.

    ``rule_files``         — list of (path, is_custom) as returned by
                             ``app.rules.router._list_rule_files()``.
    ``alert_counts_by_technique`` — ``{mitre_technique: count_in_window}``,
                             precomputed by the caller from the JSONL alert log.
                             Missing/empty ``mitre_technique`` fields in alert
                             records are counted into ``alerts_unmapped`` (not
                             bucketed here).
    ``alerts_unmapped``    — number of alerts in window whose technique is
                             missing/empty (pre-PR#14 alert records, etc.).

    Returns ``None`` when the matrix dataset is unavailable (caller returns
    503). Otherwise returns the full Navigator-style payload.
    """
    matrix = load_matrix()
    if matrix is None:
        return None

    # 1. Bucket every rule under its declared tactic(s). A rule with
    #    sub-technique ID (T1059.001) is bucketed under the PREFIX (T1059)
    #    in the dataset, matching the validator's behavior.
    rule_tactic_map: dict[str, dict[str, set[str]]] = {t: {} for t in _TACTICS}
    rules_total = 0
    rules_mapped = 0
    rules_unmapped = 0
    for path, _is_custom in rule_files:
        rules_total += 1
        try:
            data = yaml.safe_load(path.read_text())
        except Exception:
            rules_unmapped += 1
            continue
        if not isinstance(data, dict):
            rules_unmapped += 1
            continue
        tactic = data.get("mitre_tactic")
        technique = data.get("mitre_technique")
        if not tactic or not technique:
            rules_unmapped += 1
            continue
        # Resolve sub-technique to prefix for dataset lookup.
        base_id = technique.split(".", 1)[0] if "." in technique else technique
        if tactic not in _TACTIC_SET:
            rules_unmapped += 1
            continue
        bucket = rule_tactic_map[tactic].setdefault(base_id, set())
        rule_name = data.get("name") or path.stem
        if rule_name not in bucket:
            bucket.add(rule_name)
            rules_mapped += 1

    # 2. Build the full matrix. Order is dictated by the dataset file
    #    (already ATT&CK-canonical), not by _TACTICS — the dataset is the
    #    source of truth for what's covered.
    tactics_out = []
    techniques_covered_ids: set[str] = set()
    tactics_with_coverage: set[str] = set()
    alerts_total = 0
    for tac in matrix.get("tactics", []):
        tactic_name = tac.get("tactic") or ""
        if tactic_name not in _TACTIC_SET:
            log.warning(
                "MITRE matrix contains tactic %r not in _TACTICS — skipping",
                tactic_name,
            )
            continue
        techs_out = []
        covered_in_tactic = 0
        alerts_in_tactic = 0
        for tech in tac.get("techniques", []):
            tech_id = tech["id"]
            rule_names = sorted(rule_tactic_map.get(tactic_name, {}).get(tech_id, set()))
            covered = bool(rule_names)
            alerts = int(alert_counts_by_technique.get(tech_id, 0))
            alerts_total += alerts
            if covered:
                covered_in_tactic += 1
                techniques_covered_ids.add(tech_id)
                tactics_with_coverage.add(tactic_name)
                alerts_in_tactic += alerts
            techs_out.append({
                "id": tech_id,
                "name": tech.get("name") or tech_id,
                "covered": covered,
                "rules": rule_names,
                "alerts": alerts,
            })
        total_in_tactic = len(techs_out)
        tactics_out.append({
            "tactic": tactic_name,
            "total": total_in_tactic,
            "covered": covered_in_tactic,
            "coverage_pct": round(100.0 * covered_in_tactic / total_in_tactic, 2)
                if total_in_tactic else 0.0,
            "alerts": alerts_in_tactic,
            "techniques": techs_out,
        })

    techniques_total = int(matrix.get("totals", {}).get("techniques") or len(techniques_covered_ids))
    # If the dataset didn't carry totals (or it's wrong), fall back to the
    # actual unique-id count we just walked so coverage_pct is never >100.
    actual_unique = {t["id"] for tac in tactics_out for t in tac["techniques"]}
    if techniques_total < len(actual_unique):
        techniques_total = len(actual_unique)

    coverage_pct = round(100.0 * len(techniques_covered_ids) / techniques_total, 2) \
        if techniques_total else 0.0

    return {
        "matrix_version": matrix.get("version") or "unknown",
        "generated": matrix.get("generated") or "",
        "window_seconds": None,  # filled in by caller
        "stats": {
            "rules_total": rules_total,
            "rules_mapped": rules_mapped,
            "rules_unmapped": rules_unmapped,
            "techniques_covered": len(techniques_covered_ids),
            "techniques_total": techniques_total,
            "coverage_pct": coverage_pct,
            "tactics_covered": len(tactics_with_coverage),
            "tactics_total": len(tactics_out),
            "alerts_total": alerts_total,
            "alerts_unmapped": alerts_unmapped,
        },
        "tactics": tactics_out,
    }
